### ISSUE TITLE
Bug in patch creation

### ISSUE THREAD

**Issue by andrewdnolan** [E3SM-Project/mosaic#10]
Since #8 was merged I've noticed a bug in the patches for the `QU240km` mesh. (See below)

![image](https://github.com/user-attachments/assets/fdc20312-d1c5-4835-93f0-f7ce7bc41e96)

I've been able to pinpoint the problem as generating from [`6d496de`](https://github.com/E3SM-Project/mosaic/commit/6d496de39a117b0ea84a5418e81e79ea0fabd201), but still working on finding the exact line that causes this.

**Comment by xylar** [comment]
I think a `-1` became a `1` in:
```
ds[array_name] = xr.where(mask, 1, ds[array_name])
```
That might be it.

**Comment by andrewdnolan** [comment]
Yup, that'll do it. With `-1`, everything looks right: 
![Screenshot 2024-09-03 at 11 28 31 AM](https://github.com/user-attachments/assets/314556b3-ed19-4fa4-9840-492a910bd531)

I'll open a quick PR. Thanks for helping find that!
